nodeLinker: hoisted
shamefullyHoist: true

allowBuilds:
  '@google/genai': false
  '@sentry/cli': true
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
